language: php

php:
  - 7.1
  - hhvm
  - nightly

before_script:
  - composer install --prefer-source --no-interaction --dev --ignore-platform-reqs

script: phpunit

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

sudo: false
